### ISSUE TITLE
Do you need the -seqpipe- package name on PyPi?

### ISSUE THREAD

**Issue by highvight** [kpj/SeqPipe#1]
Hi there,

I kindly wanted ask if I could takeover the seqpipe project name on PyPi (you would need to delete project there) : https://pypi.org/project/seqpipe/  I created this repository https://github.com/highvight/seqpipe and now realized that the name is already taken. If you are still using this package I will think of a different name :)
Thank you very much!

**Comment by kpj** [comment]
Hey, thanks for reaching out!
This package is still a dependency in some (quite old) projects, so it is unfortunately not possible to give up the name.
Your project looks very cool! I hope you can find another fitting name :-)

**Comment by highvight** [comment]
Hey, thanks for your reply!
No worries, [streampipe](https://pypi.org/project/streampipe/) it is. Thanks anyway!
Cheers
